
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$farm_type = $block->getFarmType();

?>
<div style="margin-bottom:15px;">
    <span style="color:#066837; font-size: 13pt"> &#9658; 生活田間 \ <?php echo $farm_type; ?></span>
</div>