<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php
    $children = $block->getChildrenData('level-top', 'submenu', $columnsLimit);

    $children['有機田間']["imgSrc"] = $this->getViewFileUrl('images/think.png');
    $children['生活田間']["imgSrc"] = $this->getViewFileUrl('images/organic.png');
    $children['栽栽田間']["imgSrc"] = $this->getViewFileUrl('images/plant.png');

    // tsuyi should fix
    $children['栽栽田間']["url"] = "landowner";

?>

<nav class="navigation" role="navigation">
    <ul>
        <?php foreach ($children as $child) {?>
        <li <?php echo $child['liClass']; ?>>
            <a href="<?php echo $child['url']?>">
                <img src="<?php /* @escapeNotVerified */ echo $child['imgSrc']; ?>" alt="<?php echo $child['name']; ?>"/>
            </a>
        </li>
        <?php } ?>
    </ul>
</nav>